
package sailorboatserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://sailorboatServer/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insert", targetNamespace = "http://sailorboatServer/", className = "sailorboatserver.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://sailorboatServer/", className = "sailorboatserver.InsertResponse")
    @Action(input = "http://sailorboatServer/HelloWorld/insertRequest", output = "http://sailorboatServer/HelloWorld/insertResponse")
    public String insert(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FetchfromDatabase")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FetchfromDatabase", targetNamespace = "http://sailorboatServer/", className = "sailorboatserver.FetchfromDatabase")
    @ResponseWrapper(localName = "FetchfromDatabaseResponse", targetNamespace = "http://sailorboatServer/", className = "sailorboatserver.FetchfromDatabaseResponse")
    @Action(input = "http://sailorboatServer/HelloWorld/FetchfromDatabaseRequest", output = "http://sailorboatServer/HelloWorld/FetchfromDatabaseResponse")
    public String fetchfromDatabase(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloWorld", targetNamespace = "http://sailorboatServer/", className = "sailorboatserver.HelloWorld_Type")
    @ResponseWrapper(localName = "helloWorldResponse", targetNamespace = "http://sailorboatServer/", className = "sailorboatserver.HelloWorldResponse")
    @Action(input = "http://sailorboatServer/HelloWorld/helloWorldRequest", output = "http://sailorboatServer/HelloWorld/helloWorldResponse")
    public String helloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://sailorboatServer/", className = "sailorboatserver.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://sailorboatServer/", className = "sailorboatserver.UpdateResponse")
    @Action(input = "http://sailorboatServer/HelloWorld/updateRequest", output = "http://sailorboatServer/HelloWorld/updateResponse")
    public String update(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
